### ISSUE TITLE
Error: redis lookup timed out

### ISSUE THREAD

**Issue by alexsmartens** [heroku-examples/python-websockets-chat#17]
Hi there,
I've created a Redis add-on for my app, however I'm getting the following error:
`redis.exceptions.ConnectionError: Error -3 connecting to ec2-54-227-19-160.compute-1.amazonaws.com:20349. Lookup timed out.`
Any ideas?

**Comment by justjenu** [comment]
@alexsmartens can you please report this via our support channel, https://help.heroku.com/tickets/new?

**Comment by alexsmartens** [comment]
Thanks.
In case anyone is still having troubles with the same problem, fixing `dnspython==1.16.0` version in `requirments.txt` solves it ([reference](https://stackoverflow.com/questions/62978444/celery-cant-find-redis-in-kubernetes)).

**Comment by crcastle** [comment]
Hi @alexsmartens- Thanks! If you would like to make a PR with that change to this repo, that would be great! In the meantime, I'll find someone on our side to review and merge your PR and the other two open PRs on this repo.

Thank you!
