### ISSUE TITLE
Chat app doesn't work when deployed to Heroku

### ISSUE THREAD

**Issue by ruiwen** [heroku-examples/python-websockets-chat#5]
I've cloned the app off Github, and it seems to work when I run it locally (websocket connections get upgraded, I get the HTTP 101 response, messages are sent), but when I deploy the app to Heroku, the app seems to stop working (the Status column in DevTools shows "Finished", as opposed to "101", and the 'receive' and 'submit' endpoints are being polled continuously).

WebSockets are enabled for the app (sqc) as well, so I'm not sure if it's a configuration mistake on my end or if Heroku has WebSockets blocked. Any way I can tell for sure?

**Comment by kennethreitz** [comment]
You may want to try again, I just updated the code.
