### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by pablogb** [heroku-examples/python-websockets-chat#6]
CPU Usage is very high when a web socket connection is established. Furthermore, the CPU usage does not go down when socket is closed.

When running locally, the process reaches 100% CPU usage and stays there.

I added psutil to track CPU usage in Heroku and just running this very simple app, cpu usage is fluctuates between 35-95% (it seems to be around 60-70% most of the time).

I deployed a working copy on Heroku that prints CPU usage when it renders index.html: 

http://shielded-hamlet-9495.herokuapp.com

Is this CPU usage expected?

**Comment by csheppard** [comment]
@pablogb did you ever find a solution to the high CPU problem?

Trying to figure it out now but its still all new to me.

**Comment by pablogb** [comment]
Unfortunately no :(

The app where I had this problem was not CPU bound so it worked well even with this CPU usage.

**Comment by csheppard** [comment]
The problem seems to be with gevent.sleep(), using gevent.sleep(0.1) fixes it for me.

**Comment by kennethreitz** [comment]
fixed!
